src/main/java/com/betacom/beans/Utenze.java
package com.betacom.beans;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Utenze {
	
	private String 	username;
	private String 	password;
	private Integer	idAnagrafica;
	private Boolean attivo;
	private	Date	dataScadenza;
	private Date 	dataIns;
	private String 	userIns;
	private Date 	dataUpd;
	private String 	userUpd;
	
	private String	ruolo;
	
	private Anagrafica anagrafica;
	
		
	public Utenze() {
		super();
	}

	public Utenze(String username, String password, Integer idAnagrafica, Boolean attivo, Date dataScadenza,
			Date dataIns, String userIns, Date dataUpd, String userUpd, String ruolo) {
		super();
		this.username = username;
		this.password = password;
		this.idAnagrafica = idAnagrafica;
		this.attivo = attivo;
		this.dataScadenza = dataScadenza;
		this.dataIns = dataIns;
		this.userIns = userIns;
		this.dataUpd = dataUpd;
		this.userUpd = userUpd;
		this.ruolo = ruolo;
	}



	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public Integer getIdAnagrafica() {
		return idAnagrafica;
	}
	public void setIdAnagrafica(Integer idAnagrafica) {
		this.idAnagrafica = idAnagrafica;
	}
	public Boolean getAttivo() {
		return attivo;
	}
	public void setAttivo(Boolean attivo) {
		this.attivo = attivo;
	}	
	public Date getDataScadenza() {
		return dataScadenza;
	}

	public void setDataScadenza(Date dataScadenza) {
		this.dataScadenza = dataScadenza;
	}

	public String getDataScadenzaString() {
		if (this.dataScadenza != null) {
			SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
			return sf.format(this.dataScadenza);
		} else
			return null;
	}
	public void setDataScadenzaString(String dataScadenza) {
		SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
		try {
			this.dataScadenza = sf.parse(dataScadenza);
		} catch (ParseException e) {
			e.printStackTrace();
		}
	}
	public Date getDataIns() {
		return dataIns;
	}

	public String getDataInsString() {
		if (dataIns != null) {
			SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			return sf.format(this.dataIns);
		} else
			return null;
	}

	public void setDataIns(Date dataIns) {
		this.dataIns = dataIns;
	}

	public void setDataInsString(String dataIns) {
		if (dataIns != null && !dataIns.isEmpty()) {
			SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			try {
				this.dataIns = sf.parse(dataIns);
			} catch (ParseException e) {
				e.printStackTrace();
			}
		}else
			this.dataIns=null;
	}

	public String getUserIns() {
		return userIns;
	}

	public void setUserIns(String userIns) {
		this.userIns = userIns;
	}

	public Date getDataUpd() {
		return dataUpd;
	}

	public String getDataUpdString() {
		if (dataUpd != null) {
			SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			return sf.format(this.dataUpd);
		} else
			return null;
	}

	public void setDataUpd(Date dataUpd) {
		this.dataUpd = dataUpd;
	}

	public void setDataUpdString(String dataUpd) {
		if (dataUpd != null && !dataUpd.isEmpty()) {
			SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			try {
				this.dataUpd = sf.parse(dataUpd);
			} catch (ParseException e) {
				e.printStackTrace();
			}
		}else
			this.dataUpd = null;
	}

	public String getUserUpd() {
		return userUpd;
	}

	public void setUserUpd(String userUpd) {
		this.userUpd = userUpd;
	}

	public Anagrafica getAnagrafica() {
		return anagrafica;
	}

	public void setAnagrafica(Anagrafica anagrafica) {
		this.anagrafica = anagrafica;
	}

	public String getRuolo() {
		return ruolo;
	}

	public void setRuolo(String ruolo) {
		this.ruolo = ruolo;
	}
	
	
}

src/main/java/com/betacom/controller/UtenzeController.java
package com.betacom.controller;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Locale;

import javax.annotation.Resource;

import org.springframework.context.MessageSource;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import com.betacom.beans.Anagrafica;
import com.betacom.beans.Utenze;
import com.betacom.services.AnagraficaService;
import com.betacom.services.UtenzeService;

@Controller
@RequestMapping("/utenze")
public class UtenzeController {	
	
	private final String _FORM = "utenze/utenze_form";
	private final String _LIST = "utenze/utenze_list";
	
	@Resource
	private UtenzeService utenzeService;
	@Resource
	private AnagraficaService anagraficaService;
	
	@Resource
	private MessageSource messageSource;
	
	
	@GetMapping("/insertForm")
	public String insertForm(Model model){
		
		Utenze utenze = new Utenze();
		Calendar c = Calendar.getInstance();
		c.add(Calendar.YEAR, 1);
		utenze.setDataScadenza(c.getTime());
		model.addAttribute("utenze", utenze);
		model.addAttribute("mode", "insert");
		ArrayList<Anagrafica> anagraficaList = anagraficaService.read();
		model.addAttribute("anagraficaList",anagraficaList);
		return _FORM;
	}
	
	@PostMapping("/insert")
	public String insert(Utenze utenze,Model model, Locale locale){
		utenzeService.insert(utenze);
		String[] dati = new String[] {utenze.getUsername()};
		String messaggio = messageSource.getMessage("utenze.message.insert.ok", dati, locale);
		model.addAttribute("messaggio",messaggio);
		return this.selectList(model);
	}
	
	@GetMapping("/updateForm/{username}")
	public String update(Model model,@PathVariable("username") String username) {
		Utenze utenze = utenzeService.read(username);
		Calendar c = Calendar.getInstance();
		c.add(Calendar.YEAR, 1);
		utenze.setDataScadenza(c.getTime());
		model.addAttribute("utenze", utenze);
		model.addAttribute("mode", "update");
		ArrayList<Anagrafica> anagraficaList = anagraficaService.read();
		model.addAttribute("anagraficaList",anagraficaList);
		return _FORM;
	}
	
	@PostMapping("/update")
	public String update(Utenze utenze,Model model){
		utenzeService.update(utenze);	
		return this.selectList(model);
	}
	
	@GetMapping("/delete/{username}")
	public String delete(@PathVariable("username") String username,Model model) {
		utenzeService.delete(username);
		return this.selectList(model);
	}
	
	@GetMapping("/select/{username}")
	public String selectSingle(	@PathVariable("username") String username,
								Model model) {		
		Utenze utenze = utenzeService.read(username);		
		model.addAttribute("utenze", utenze);		
		return _FORM;
	}
	

	@RequestMapping({"","/select"})
	public String selectList(Model model) {
		ArrayList<Utenze> listaUtenze = utenzeService.read();
		model.addAttribute("listaUtenze",listaUtenze);
		return _LIST;
	}	
	
}

src/main/webapp/WEB-INF/jsp/utenze/utenze_form.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>HrManager</title>
<link rel="stylesheet"
	href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
	integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
	crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="<s:url value="/css/custom.css"></s:url>">
<script type="text/javascript"
	src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script
	src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
	integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
	crossorigin="anonymous"></script>
<script
	src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
	integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
	crossorigin="anonymous"></script>

</head>

<c:choose>
	<c:when test="${mode == 'insert'}">
		<s:url value="/utenze/insert" var="action"></s:url>
	</c:when>
	<c:when test="${mode == 'update'}">
		<s:url value="/utenze/update" var="action"></s:url>
	</c:when>
</c:choose>

<body class="bg-white">

	<nav
		class="navbar navbar-expand-lg navbar-light shadow-sm bg-white fixed-top"
		style="opacity: 0.8"
		>
		<a class="navbar-brand" href="#"> <img
			src="https://www.betacom.it/wp-content/uploads/2018/10/logo_betacom-2.png"
			height="30" alt="">
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse"
			data-target="#navbarText" aria-controls="navbarText"
			aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarText">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link"	href="<s:url value="/homepage"/>">
					<s:message code="menu.home" /></a>
				</li>
				<li class="nav-item"><a class="nav-link"
					href="<s:url value="/anagrafica"/>"><s:message
							code="menu.anagrafica" /></a></li>
				<li class="nav-item active"><a class="nav-link"
					href="<s:url value="/utenze"/>"><s:message code="menu.utenze" /></a>
				</li>
				<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
					role="button" data-toggle="dropdown" aria-haspopup="true"
					aria-expanded="false"> <s:message code="menu.system" />
				</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="<s:url value="/stati"/>"><s:message
								code="menu.system.stati" /></a> <a class="dropdown-item"
							href="<s:url value="/province"/>"><s:message
								code="menu.system.province" /></a> <a class="dropdown-item"
							href="<s:url value="/citta"/>"><s:message
								code="menu.system.citta" /></a>
					</div></li>
			</ul>
			<a class="navbar-text nav-link" href="/logout"> Logout </a>
		</div>
	</nav>

	
	<div class="jumbotron jumbotron-fluid text-white"
		style="background-image: url('https://webdaytona.com/cwsd.php?Z3AuPTQ0Pg/NDI/NEAiNjE2MzcjRTJRSi44OSAjIDtJT1QoISVEIDkhTVU2MlY2Km92YGk.jpeg'); background-position: center center;">
		<div class="container mb-4 pt-5 text-center" style="text-shadow: 1px 1px 2px #000000;">

			<c:choose>
				<c:when test="${mode == 'insert'}">
					<h1 class="display-4 font-weight-bold">
						<s:message code="utenze.title.insert" />
					</h1>
				</c:when>
				<c:when test="${mode == 'update'}">
					<h1 class="display-4 font-weight-bold">
						<s:message code="utenze.title.update" />
					</h1>
				</c:when>
			</c:choose>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-12 bg-white mt-4 mb-4 pt-4 rounded border shadow">
				<form action="${action}" method="post">
					<div class="form-row">
						<div class="form-group col-md-12 col-xs-12 required">
							<label for="username"><s:message code="utenze.username" /></label>
							<input type="text" class="form-control" name="username"
								id="username" value="${utenze.username}"  ${mode=='update'?'readonly':'' } required>
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-md-12 col-xs-12 required">
							<label for="password"><s:message code="utenze.password" /></label> <input
								type="password" class="form-control" name="password" id="password"
								value="${utenze.password}" required>
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-md-12 col-xs-12 required">
							<label for="ruolo"><s:message code="utenze.ruolo" /></label>
							<select class="form-control" id="ruolo" name="ruolo">
								<option value="UTENTE" ${utenze.ruolo!='ADMIN'?'selected':'' }>Utente</option>
								<option value="ADMIN" ${utenze.ruolo=='ADMIN'?'selected':'' }>Admin</option>
							</select>
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-md-12 col-xs-12 required">
							<label for="anagrafica"><s:message
									code="utenze.anagrafica" /></label>
							<select id="anagrafica" class="form-control" name="${mode=='insert'?'idAnagrafica':''}" ${mode=='update'?'disabled':''} >
								<option></option>
								<c:forEach items="${anagraficaList}" var="anagrafica"> 
									<option value="${anagrafica.idAnagrafica}" ${utenze.idAnagrafica==anagrafica.idAnagrafica?'selected':''}>${anagrafica.cognome} ${anagrafica.nome}</option>
								</c:forEach>
							</select>	
							<c:if test="${mode=='update'}">
								<input type="hidden" name="idAnagrafica" value="${utenze.idAnagrafica}">
							</c:if>		
						</div>
					</div>
					<div class="form-row">
						<label class="d-block pr-2"><s:message
									code="utenze.attivo" />:</label>
							<div class="form-check form-check-inline">
								<input class="form-check-input" type="radio" id="attivo_si"
									name="attivo" value="true"
									${utenze.attivo!=false?'checked':''}> <label
									class="form-check-label" for="attivo_si"><s:message
										code="button.si" /></label>
							</div>
							<div class="form-check form-check-inline">
								<input class="form-check-input" type="radio" id="attivo_no"
									value="false" name="attivo"
									${utenze.attivo==false?'checked':''}> <label
									class="form-check-label" for="attivo_no"><s:message
										code="button.no" /></label>
							</div>		
					</div>
					
					<div class="form-row">
						<div class="form-group col-md-12 pt-4 pb-5">
							<button type="submit" class="btn btn-primary">
								<s:message code="button.salva" />
							</button>
						</div>
					</div>
					<input type="hidden" name="dataInsString" value="${utenze.dataInsString}"><br/>
					<input type="hidden" name="dataUpdString" value="${utenze.dataUpdString}"><br/>
					<input type="hidden" name="userIns" value="${utenze.userIns}"><br/>
					<input type="hidden" name="userUpd" value="${utenze.userUpd}"><br/>
				</form>
			</div>
		</div>
	</div>
</body>

</html>

src/main/webapp/WEB-INF/jsp/utenze/utenze_list.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>HrManager</title>
<link rel="stylesheet"
	href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
	integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
	crossorigin="anonymous">

<script type="text/javascript"
	src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script
	src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
	integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
	crossorigin="anonymous"></script>
<script
	src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
	integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
	crossorigin="anonymous"></script>

<script type="text/javascript"
	src='<s:url value="/js/myPage.js"></s:url>'></script>

</head>

<s:url value="/utenze/insertForm" var="insert"></s:url>
<s:url value="/utenze/updateForm" var="update"></s:url>
<s:url value="/utenze/delete" var="delete"></s:url>



<body class="bg-white">

		<nav
		class="navbar navbar-expand-lg navbar-light shadow-sm bg-white fixed-top"
		style="opacity: 0.8"
		>
		<a class="navbar-brand" href="#"> <img
			src="https://www.betacom.it/wp-content/uploads/2018/10/logo_betacom-2.png"
			height="30" alt="">
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse"
			data-target="#navbarText" aria-controls="navbarText"
			aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarText">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link"	href="<s:url value="/homepage"/>">
					<s:message code="menu.home" /></a>
				</li>
				<li class="nav-item"><a class="nav-link"
					href="<s:url value="/anagrafica"/>"><s:message
							code="menu.anagrafica" /></a></li>
				<li class="nav-item active"><a class="nav-link"
					href="<s:url value="/utenze"/>"><s:message code="menu.utenze" /></a>
				</li>
				<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
					role="button" data-toggle="dropdown" aria-haspopup="true"
					aria-expanded="false"> <s:message code="menu.system" />
				</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="<s:url value="/stati"/>"><s:message
								code="menu.system.stati" /></a> <a class="dropdown-item"
							href="<s:url value="/province"/>"><s:message
								code="menu.system.province" /></a> <a class="dropdown-item"
							href="<s:url value="/citta"/>"><s:message
								code="menu.system.citta" /></a>
					</div></li>
			</ul>
			<a class="navbar-text nav-link" href="/logout"> Logout </a>
		</div>
	</nav>

	
	<div class="jumbotron jumbotron-fluid text-white"
		style="background-image: url('https://webdaytona.com/cwsd.php?Z3AuPTQ0Pg/NDI/NEAiNjE2MzcjRTJRSi44OSAjIDtJT1QoISVEIDkhTVU2MlY2Km92YGk.jpeg'); background-position: center center;">
		<div class="container mb-4 pt-5 text-center" style="text-shadow: 1px 1px 2px #000000;">

		<h1 class="display-4 font-weight-bold">
			<s:message code="utenze.title" />
		</h1>
	
		</div>
	</div>
	<div class="container-fluid bg-white mt-4 pt-3">
		<div class="row">
			<div class="col-12">
				<table class="table">
					<thead class="thead-light">
						<tr>
							<th scope="col"><s:message code="utenze.username" /></th>
							<th scope="col"><s:message code="anagrafica.cognome" /></th>
							<th scope="col"><s:message code="anagrafica.nome" /></th>
							<th scope="col"><s:message code="utenze.ruolo" /></th>
							<th scope="col"><s:message code="utenze.attivo" /></th>
							<th scope="col"><s:message code="utenze.dataScadenza" /></th>
							
							<th scope="col" class="text-center">
								<a href="${insert}" class="btn btn-success btn-sm" role="button"> 
									<s:message code="button.inserisci" />
								</a>
							</th>
						</tr>
					</thead>
					<tbody>
						<c:forEach items="${listaUtenze}" var="utenze">
							<tr>
								<td>${utenze.username}</td>
								<td>${utenze.anagrafica.cognome}</td>
								<td>${utenze.anagrafica.nome}</td>
								<td>${utenze.ruolo}</td>
								<td>${utenze.attivo}</td>
								<td>${utenze.dataScadenzaString}</td>
								
								<td class="text-center">
									<div class="btn-group" role="group">
										<a 	href="${update}/${utenze.username}"
											class="btn btn-info btn-sm" role="button">
											<s:message code="button.modifica" />
										</a> 
										<a 	href="${delete}/${utenze.username}"
											class="btn btn-danger btn-sm" role="button">
											<s:message code="button.elimina" />
										</a>
									</div>
								</td>
							</tr>
						</c:forEach>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</body>
</html>